'use client'

import React, { useState, useEffect, useCallback, useMemo } from 'react'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { Input } from '@/components/ui/input'
import { Loader2, Printer, AlertTriangle, Barcode, Search, X } from 'lucide-react'

interface Product {
  id: string
  code: string
  barcode?: string | null
  name: string
}

interface BarcodePrintModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  products: Product[]
}

function toFaNum(n: number | string | null | undefined): string {
  if (n === null || n === undefined) return '۰'
  return String(n).replace(/\d/g, (d) => '۰۱۲۳۴۵۶۷۸۹'[parseInt(d)])
}

// ★ تشخیص بارکد تولید شده با دکمه "تولید بارکد" در مودال
// بارکدهای تولید شده با دکمه با 629123 شروع می‌شوند و ۱۳ رقمی هستند
function isAutoGeneratedBarcode(barcode?: string | null): boolean {
  if (!barcode || !barcode.trim()) return false
  const trimmed = barcode.trim()
  return trimmed.startsWith('629123') && trimmed.length === 13 && /^\d{13}$/.test(trimmed)
}

export function BarcodePrintModal({
  open,
  onOpenChange,
  products,
}: BarcodePrintModalProps) {
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set())
  const [printing, setPrinting] = useState(false)
  const [paperSize, setPaperSize] = useState<'a4' | 'a5'>('a4')
  const [showOnlyWithBarcode, setShowOnlyWithBarcode] = useState(true)
  const [searchQuery, setSearchQuery] = useState('')

  // ★ فقط کالاهای که بارکد تولید شده با دکمه دارند
  const productsWithAutoBarcode = useMemo(
    () => products.filter((p) => isAutoGeneratedBarcode(p.barcode)),
    [products]
  )

  // ★ کالاها دارای هر نوع بارکد (برای چاپ)
  const productsWithAnyBarcode = useMemo(
    () => products.filter((p) => p.barcode && p.barcode.trim()),
    [products]
  )

  // ★ لیست نمایشی (بر اساس فیلتر فقط بارکدهای تولید شده)
  const displayProducts = useMemo(() => {
    let list = showOnlyWithBarcode ? productsWithAutoBarcode : products

    if (searchQuery.trim()) {
      const q = searchQuery.trim().toLowerCase()
      list = list.filter(
        (p) =>
          p.name.toLowerCase().includes(q) ||
          p.code.toLowerCase().includes(q) ||
          (p.barcode && p.barcode.includes(searchQuery))
      )
    }

    return list
  }, [products, productsWithAutoBarcode, showOnlyWithBarcode, searchQuery])

  const selectableCount = useMemo(
    () => displayProducts.filter((p) => isAutoGeneratedBarcode(p.barcode)).length,
    [displayProducts]
  )

  useEffect(() => {
    if (open) {
      setSelectedIds(new Set())
      setShowOnlyWithBarcode(true)
      setSearchQuery('')
    }
  }, [open])

  const toggleSelect = (id: string) => {
    setSelectedIds((prev) => {
      const next = new Set(prev)
      next.has(id) ? next.delete(id) : next.add(id)
      return next
    })
  }

  const toggleAll = () => {
    const selectableProducts = displayProducts.filter(
      (p) => isAutoGeneratedBarcode(p.barcode)
    )
    const allSelected = selectableProducts.every((p) => selectedIds.has(p.id))

    if (allSelected) {
      setSelectedIds(new Set())
    } else {
      setSelectedIds(new Set(selectableProducts.map((p) => p.id)))
    }
  }

  // ★ چاپ فقط بارکدهای تولید شده (که قابل چاپ هستند)
  const selectedProducts = productsWithAnyBarcode.filter((p) =>
    selectedIds.has(p.id)
  )

  const handlePrint = useCallback(() => {
    if (selectedProducts.length === 0) return
    setPrinting(true)

    const cols = paperSize === 'a4' ? 3 : 2
    const pageWidth = paperSize === 'a4' ? '210mm' : '148mm'
    const pageHeight = paperSize === 'a4' ? '297mm' : '210mm'
    const itemHeight = paperSize === 'a4' ? '85px' : '70px'
    const barcodeHeight = paperSize === 'a4' ? 55 : 40

    const printHTML = `
      <!DOCTYPE html>
      <html dir="rtl">
      <head>
        <meta charset="UTF-8">
        <title>چاپ بارکد</title>
        <script src="https://cdn.jsdelivr.net/npm/jsbarcode@3.11.5/dist/JsBarcode.all.min.js"><\/script>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          @page {
            size: ${pageWidth} ${pageHeight};
            margin: 8mm;
          }
          body {
            font-family: Tahoma, Arial, sans-serif;
            background: white;
          }
          .grid {
            display: grid;
            grid-template-columns: repeat(${cols}, 1fr);
            gap: 4px;
            width: 100%;
          }
          .item {
            border: 1px solid #ddd;
            padding: 4px;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: ${itemHeight};
            overflow: hidden;
          }
          .item img { max-width: 100%; height: auto; }
          .item-name { font-size: 9px; font-weight: bold; text-align: center; margin-top: 2px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 100%; }
          .item-code { font-size: 8px; color: #666; }
          .page-break { page-break-before: always; }
        </style>
      </head>
      <body>
        <div class="grid" id="barcodeGrid">
          ${selectedProducts
            .map(
              (p, i) => `
            <div class="item" data-barcode="${p.barcode}" data-name="${p.name}" data-code="${p.code}">
              <svg id="barcode-${i}"></svg>
              <div class="item-name">${p.name}</div>
              <div class="item-code">کد: ${p.code}</div>
            </div>
          `
            )
            .join('')}
        </div>
        <script>
          window.onload = function() {
            ${selectedProducts
              .map(
                (p, i) => `
              try {
                JsBarcode("#barcode-${i}", "${p.barcode}", {
                  format: "EAN13",
                  width: 2,
                  height: ${barcodeHeight},
                  margin: 3,
                  displayValue: true,
                  fontSize: 10,
                });
              } catch(e) {
                document.getElementById("barcode-${i}").outerHTML = 
                  '<div style="font-size:14px;font-family:monospace;letter-spacing:2px;">${p.barcode}</div>';
              }
            `
              )
              .join('')}
            setTimeout(function() { window.print(); window.close(); }, 800);
          };
        <\/script>
      </body>
      </html>
    `

    const printWindow = window.open('', '_blank', 'width=800,height=600')
    if (printWindow) {
      printWindow.document.write(printHTML)
      printWindow.document.close()
    }

    setPrinting(false)
  }, [selectedProducts, paperSize])

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent
        className="max-w-[750px] w-[calc(100%-1.5rem)] max-h-[85vh] overflow-y-auto"
        dir="rtl"
      >
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-sm sm:text-base">
            <Printer className="w-4 h-4 text-emerald-600" />
            چاپ بارکد کالاها
          </DialogTitle>
          <DialogDescription className="text-xs">
            فقط کالاهای که با دکمه «تولید بارکد» بارکد گرفته‌اند قابل چاپ هستند
          </DialogDescription>
        </DialogHeader>

        {products.length === 0 ? (
          <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 flex items-center gap-2 justify-center">
            <AlertTriangle className="w-4 h-4 text-amber-600 flex-shrink-0" />
            <p className="text-sm text-amber-700">
              هیچ کالای ثبت نشده است.
            </p>
          </div>
        ) : (
          <div className="space-y-4">
            <div className="space-y-3 bg-gray-50 p-3 rounded-lg">
              <div className="flex items-center gap-4 flex-wrap">
                <div className="flex items-center gap-2">
                  <Label className="text-xs font-medium shrink-0">سایز کاغذ:</Label>
                  <div className="flex gap-2">
                    <button
                      onClick={() => setPaperSize('a4')}
                      className={`px-3 py-1 text-xs rounded border transition-colors ${
                        paperSize === 'a4'
                          ? 'bg-emerald-600 text-white border-emerald-600'
                          : 'bg-white text-gray-600 border-gray-300 hover:border-emerald-400'
                      }`}
                    >
                      A4
                    </button>
                    <button
                      onClick={() => setPaperSize('a5')}
                      className={`px-3 py-1 text-xs rounded border transition-colors ${
                        paperSize === 'a5'
                          ? 'bg-emerald-600 text-white border-emerald-600'
                          : 'bg-white text-gray-600 border-gray-300 hover:border-emerald-400'
                      }`}
                    >
                      A5
                    </button>
                  </div>
                </div>
                <div className="mr-auto text-[11px] text-gray-500">
                  {paperSize === 'a4' ? '۳ ستون × ۸ ردیف (۲۴ بارکد)' : '۲ ستون × ۶ ردیف (۱۲ بارکد)'}
                </div>
              </div>

              <div className="flex items-center justify-between pt-2 border-t border-gray-200 flex-wrap gap-2">
                <div className="flex items-center gap-2">
                  <Checkbox
                    id="only-barcode"
                    checked={showOnlyWithBarcode}
                    onCheckedChange={(checked) => setShowOnlyWithBarcode(Boolean(checked))}
                  />
                  <Label htmlFor="only-barcode" className="text-xs cursor-pointer flex items-center gap-1.5">
                    <Barcode className="w-3.5 h-3.5 text-emerald-600" />
                    فقط کالاها دارای بارکد تولید شده
                  </Label>
                </div>
                <div className="flex items-center gap-2 text-[11px] flex-wrap">
                  <Badge variant="outline" className="border-emerald-300 text-emerald-700 bg-emerald-50">
                    {toFaNum(productsWithAutoBarcode.length)} تولید شده
                  </Badge>
                  <Badge variant="outline" className="border-gray-300 text-gray-600 bg-gray-50">
                    {toFaNum(products.length - productsWithAutoBarcode.length)} بدون بارکد تولید شده
                  </Badge>
                </div>
              </div>

              <div className="relative pt-2 border-t border-gray-200">
                <Search className="absolute right-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-400 mt-1" />
                <Input
                  type="text"
                  placeholder="جستجو در نام، کد یا بارکد..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pr-9 pl-9 h-8 text-xs bg-white"
                />
                {searchQuery && (
                  <button
                    onClick={() => setSearchQuery('')}
                    className="absolute left-3 top-1/2 -translate-y-1/2 mt-1"
                  >
                    <X className="w-3.5 h-3.5 text-gray-400 hover:text-gray-600" />
                  </button>
                )}
              </div>
            </div>

            <div className="flex items-center justify-between px-1 flex-wrap gap-2">
              <div className="flex items-center gap-2">
                <Checkbox
                  id="select-all"
                  checked={
                    selectableCount > 0 &&
                    displayProducts
                      .filter((p) => isAutoGeneratedBarcode(p.barcode))
                      .every((p) => selectedIds.has(p.id))
                  }
                  onCheckedChange={toggleAll}
                  disabled={selectableCount === 0}
                />
                <Label htmlFor="select-all" className="text-xs cursor-pointer">
                  انتخاب همه ({toFaNum(selectableCount)} کالا دارای بارکد تولید شده)
                </Label>
              </div>
              {selectedIds.size > 0 && (
                <span className="text-xs bg-emerald-100 text-emerald-700 px-2 py-0.5 rounded-full font-medium">
                  {toFaNum(selectedIds.size)} انتخاب‌شده
                </span>
              )}
            </div>

            <div className="border rounded-lg overflow-hidden">
              <div className="max-h-[320px] overflow-y-auto">
                <Table>
                  <TableHeader className="bg-gray-50 sticky top-0 z-10">
                    <TableRow>
                      <TableHead className="w-10 text-center"></TableHead>
                      <TableHead className="text-right text-xs">کد</TableHead>
                      <TableHead className="text-right text-xs">
                        نام کالا
                      </TableHead>
                      <TableHead className="text-right text-xs">
                        بارکد
                      </TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {displayProducts.length === 0 ? (
                      <TableRow>
                        <TableCell colSpan={4} className="text-center py-6 text-gray-400 text-xs">
                          کالای یافت نشد
                        </TableCell>
                      </TableRow>
                    ) : (
                      displayProducts.map((product) => {
                        const hasAutoBarcode = isAutoGeneratedBarcode(product.barcode)
                        const isSelected = selectedIds.has(product.id)

                        return (
                          <TableRow
                            key={product.id}
                            className={`transition-colors ${
                              hasAutoBarcode
                                ? `cursor-pointer hover:bg-gray-50 ${isSelected ? 'bg-emerald-50' : ''}`
                                : 'opacity-50 bg-gray-50/30'
                            }`}
                            onClick={() => hasAutoBarcode && toggleSelect(product.id)}
                          >
                            <TableCell className="text-center">
                              <Checkbox
                                checked={isSelected}
                                onCheckedChange={() => hasAutoBarcode && toggleSelect(product.id)}
                                onClick={(e) => e.stopPropagation()}
                                disabled={!hasAutoBarcode}
                              />
                            </TableCell>
                            <TableCell className="text-xs font-mono" dir="ltr">
                              {toFaNum(product.code)}
                            </TableCell>
                            <TableCell className="text-xs font-medium">
                              <div className="flex items-center gap-1.5">
                                <span className="truncate max-w-[150px]">{product.name}</span>
                                {hasAutoBarcode && (
                                  <span title="بارکد تولید شده با دکمه" className="inline-flex shrink-0">
                                    <Barcode className="w-3.5 h-3.5 text-emerald-600" />
                                  </span>
                                )}
                              </div>
                            </TableCell>
                            <TableCell
                              className="text-xs font-mono text-gray-600"
                              dir="ltr"
                            >
                              {hasAutoBarcode ? (
                                <span className="bg-emerald-50 border border-emerald-200 px-1.5 py-0.5 rounded text-[11px] text-emerald-700">
                                  {toFaNum(product.barcode!)}
                                </span>
                              ) : product.barcode && product.barcode.trim() ? (
                                <span className="bg-gray-100 px-1.5 py-0.5 rounded text-[11px] text-gray-500">
                                  {toFaNum(product.barcode)}
                                </span>
                              ) : (
                                <span className="text-gray-400">—</span>
                              )}
                            </TableCell>
                          </TableRow>
                        )
                      })
                    )}
                  </TableBody>
                </Table>
              </div>
            </div>

            <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
              <p className="text-[11px] text-blue-700 leading-relaxed">
                💡 <strong>راهنما:</strong> فقط کالاهای که با دکمه «تولید بارکد» در مودال افزودن کالا بارکد گرفته‌اند قابل چاپ هستند.
                بارکدهای اسکن شده یا دستی وارد شده قابل چاپ از این مودال نمی‌باشند.
              </p>
            </div>
          </div>
        )}

        <DialogFooter className="gap-2 sm:gap-0">
          <Button
            variant="outline"
            onClick={() => onOpenChange(false)}
            className="text-xs h-9"
          >
            بستن
          </Button>
          <Button
            onClick={handlePrint}
            disabled={selectedIds.size === 0 || printing}
            className="bg-emerald-600 hover:bg-emerald-700 gap-1.5 text-xs h-9"
          >
            {printing ? (
              <Loader2 className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <Printer className="w-3.5 h-3.5" />
            )}
            چاپ {selectedIds.size > 0 ? `(${toFaNum(selectedIds.size)})` : ''}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

export default BarcodePrintModal