'use client'

// ============================================================================
// src/components/products/products-page.tsx (v9.3.0 - FINAL)
// ★ ستون ارزش موجودی + آفلاین کامل + CustomSwitch + JWT Auth
// ★ v9.3: رفع باگ‌های مودال ثبت/ویرایش کالا
//   - تشخیص بارکد تکراری (فوری هنگام تایپ)
//   - اجباری بودن دسته‌بندی و واحد
//   - جلوگیری از بسته شدن مودال با کلیک بیرون
//   - در حالت Create: مودال باز می‌ماند (برای ثبت چند کالا)
//   - در حالت Edit: مودال بسته می‌شود
// ============================================================================

import { useState, useEffect, useCallback, useMemo } from 'react'
import { useAppStore } from '@/lib/store'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent } from '@/components/ui/card'
import { Checkbox } from '@/components/ui/checkbox'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import {
  Package,
  Plus,
  Search,
  Edit2,
  Trash2,
  AlertTriangle,
  Loader2,
  Filter,
  RefreshCw,
  Printer,
  Barcode,
  Wand2,
  WifiOff,
  Upload,
  CloudOff,
  TrendingUp,
  AlertCircle,
} from 'lucide-react'
import { useToast } from '@/hooks/use-toast'
import { BarcodePrintModal } from './barcode-print-modal'

// ══════════════════════════
// Helpers
// ══════════════════════════
function toFaNum(n: number | string | null | undefined): string {
  if (n === null || n === undefined) return '۰'
  return String(n).replace(/\d/g, (d) => '۰۱۲۳۴۵۶۷۸۹'[parseInt(d)])
}

function getAuthHeaders(): Record<string, string> {
  const token = typeof window !== 'undefined' ? localStorage.getItem('token') : null
  return {
    'Content-Type': 'application/json',
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
  }
}

// ★ تشخیص بارکد تولید شده با دکمه "تولید بارکد"
function isAutoGeneratedBarcode(barcode?: string | null): boolean {
  if (!barcode || !barcode.trim()) return false
  const trimmed = barcode.trim()
  return trimmed.startsWith('629123') && trimmed.length === 13 && /^\d{13}$/.test(trimmed)
}

// ★ محاسبه ارزش کل موجودی یک کالا (موجودی × قیمت فروش)
function calculateTotalValue(currentStock: number, salePrice: number): number {
  return (currentStock || 0) * (salePrice || 0)
}

// ★ CustomSwitch: آبی برای فعال، خاکستری برای غیرفعال (RTL-safe)
function CustomSwitch({
  checked,
  onCheckedChange,
  disabled = false,
}: {
  checked: boolean
  onCheckedChange: (v: boolean) => void
  disabled?: boolean
}) {
  return (
    <button
      type="button"
      role="switch"
      aria-checked={checked}
      disabled={disabled}
      onClick={() => onCheckedChange(!checked)}
      className={`relative inline-flex h-6 w-11 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none ${
        disabled ? 'opacity-50 cursor-not-allowed' : ''
      } ${checked ? 'bg-blue-600' : 'bg-gray-300'}`}
    >
      <span className="sr-only">وضعیت فعال</span>
      <span
        aria-hidden="true"
        className={`pointer-events-none absolute top-0 h-5 w-5 rounded-full bg-white shadow ring-0 transition-all duration-200 ease-in-out ${
          checked ? 'right-0' : 'left-0'
        }`}
      />
    </button>
  )
}

// ★ کامپوننت نمایش ارزش موجودی در جدول Desktop
function StockValueBadge({ currentStock, salePrice }: { currentStock: number; salePrice: number }) {
  const totalValue = calculateTotalValue(currentStock, salePrice)
  if (totalValue <= 0) {
    return <span className="text-gray-300 text-[11px]">—</span>
  }
  return (
    <span className="text-xs font-bold text-emerald-700" dir="rtl">
      {formatPrice(totalValue)}
    </span>
  )
}

// ★ کامپوننت نمایش ارزش موجودی در کارت موبایل
function StockValueCard({ currentStock, salePrice }: { currentStock: number; salePrice: number }) {
  const totalValue = calculateTotalValue(currentStock, salePrice)
  if (totalValue <= 0) return null
  return (
    <div className="mt-2 pt-2 border-t border-emerald-200 bg-emerald-50/50 rounded-lg px-2.5 py-2 flex items-center justify-between">
      <div className="flex items-center gap-1.5">
        <div className="w-6 h-6 rounded-md bg-emerald-500 flex items-center justify-center shrink-0">
          <TrendingUp className="w-3 h-3 text-white" />
        </div>
        <span className="text-[10px] text-emerald-700 font-medium">ارزش موجودی:</span>
      </div>
      <span className="text-xs font-bold text-emerald-800" dir="rtl">
        {formatPrice(totalValue)}
      </span>
    </div>
  )
}

function formatToPersianWithCommas(value: string): string {
  if (!value) return ''
  const raw = value.replace(/[^\d\u06F0-\u06F9\u0660-\u0669]/g, '')
  if (!raw) return ''
  const eng = raw
    .replace(/[\u06F0-\u06F9]/g, (d) => String.fromCharCode(d.charCodeAt(0) - 0x06F0 + 0x0030))
    .replace(/[\u0660-\u0669]/g, (d) => String.fromCharCode(d.charCodeAt(0) - 0x0660 + 0x0030))
  const num = parseInt(eng, 10)
  if (isNaN(num)) return ''
  return toFaNum(num.toLocaleString('en-US'))
}

function parsePersianNumber(value: string): number {
  if (!value) return 0
  const raw = value.replace(/[^\d\u06F0-\u06F9\u0660-\u0669]/g, '')
  if (!raw) return 0
  const eng = raw
    .replace(/[\u06F0-\u06F9]/g, (d) => String.fromCharCode(d.charCodeAt(0) - 0x06F0 + 0x0030))
    .replace(/[\u0660-\u0669]/g, (d) => String.fromCharCode(d.charCodeAt(0) - 0x0660 + 0x0030))
  return parseFloat(eng) || 0
}

function formatPrice(price: number | string): string {
  const num = typeof price === 'string' ? parseFloat(price) : price
  if (isNaN(num)) return '۰ ریال'
  return `${toFaNum(Math.round(num).toLocaleString('en-US'))} ریال`
}

function getUnitLabel(u: Unit): string {
  return u.nameFa || u.name
}

// ★ ترتیب واحدها با "بطری" و "دستگاه"
const PREFERRED_UNITS = [
  'عدد', 'کیلوگرم', 'گرم', 'بسته', 'کارتن', 'بطری', 'دستگاه', 'جعبه',
  'متر', 'سانتی متر', 'میلی متر', 'لیتر', 'میلی لیتر',
  'حلقه', 'جفت', 'تن', 'جین', 'دسته', 'کیسه'
]

function sortUnits(unitsList: Unit[]): Unit[] {
  return [...unitsList].sort((a, b) => {
    const nameA = a.nameFa || a.name
    const nameB = b.nameFa || b.name
    const indexA = PREFERRED_UNITS.indexOf(nameA)
    const indexB = PREFERRED_UNITS.indexOf(nameB)
    if (indexA === -1 && indexB === -1) return 0
    if (indexA === -1) return 1
    if (indexB === -1) return -1
    return indexA - indexB
  })
}

// ══════════════════════════
// Types
// ══════════════════════════
interface Product {
  id: string
  code: string
  barcode?: string | null
  name: string
  categoryId?: string | null
  unitId?: string | null
  unitLabel?: string
  purchasePrice: number
  salePrice: number
  taxRate: number
  currentStock: number
  minStock: number
  isActive: boolean
  tenantId?: string | null
  createdAt: string
  category?: { id: string; name: string } | null
  unit?: {
    id: string
    name: string
    nameFa: string
    symbol: string | null
  } | null
  _isOffline?: boolean
  _offlineId?: string
  _offlineAction?: 'create' | 'update' | 'delete'
  _syncStatus?: 'pending' | 'syncing' | 'failed'
}

interface Category {
  id: string
  name: string
  isActive: boolean
  productCount?: number
}

interface Unit {
  id: string
  name: string
  nameFa: string
  symbol: string | null
  isDefault?: boolean
}

interface PlanLimits {
  maxProducts: number
  currentCount: number
  remaining: number
  canAdd: boolean
  planTierName: string
}

interface AddForm {
  name: string
  code: string
  barcode: string
  generateBarcode: boolean
  categoryId: string
  unitId: string
  purchasePrice: string
  salePrice: string
  taxRate: string
  minStock: string
  isActive: boolean
}

const INITIAL_ADD_FORM: AddForm = {
  name: '',
  code: '',
  barcode: '',
  generateBarcode: false,
  categoryId: 'none',
  unitId: 'none',
  purchasePrice: '0',
  salePrice: '0',
  taxRate: '0',
  minStock: '5',
  isActive: true,
}

// ══════════════════════════════════════════════════════════════════
// کامپوننت اصلی
// ══════════════════════════════════════════════════════════════════
export default function ProductsPage() {
  const tenantId = useAppStore((s) => s.tenantId)
  const isOnline = useAppStore((s) => s.isOnline)

  const [products, setProducts] = useState<Product[]>([])
  const [allProducts, setAllProducts] = useState<Product[]>([])
  const [categories, setCategories] = useState<Category[]>([])
  const [units, setUnits] = useState<Unit[]>([])
  const [planLimits, setPlanLimits] = useState<PlanLimits | null>(null)
  const [loading, setLoading] = useState(true)
  const [isSyncing, setIsSyncing] = useState(false)

  const [page, setPage] = useState(1)
  const [totalPages, setTotalPages] = useState(1)
  const [total, setTotal] = useState(0)
  const [searchInput, setSearchInput] = useState('')
  const [search, setSearch] = useState('')
  const [selectedCategory, setSelectedCategory] = useState<string>('all')

  const [addDialogOpen, setAddDialogOpen] = useState(false)
  const [editDialogOpen, setEditDialogOpen] = useState(false)
  const [printModalOpen, setPrintModalOpen] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [generatingCode, setGeneratingCode] = useState(false)

  // ★ v9.3: state‌های جدید برای validation بارکد تکراری
  const [addBarcodeError, setAddBarcodeError] = useState<string>('')
  const [addBarcodeIsDuplicate, setAddBarcodeIsDuplicate] = useState(false)
  const [editBarcodeError, setEditBarcodeError] = useState<string>('')
  const [editBarcodeIsDuplicate, setEditBarcodeIsDuplicate] = useState(false)

  const [addForm, setAddForm] = useState<AddForm>(INITIAL_ADD_FORM)
  const [editForm, setEditForm] = useState({
    id: '',
    name: '',
    code: '',
    barcode: '',
    categoryId: 'none',
    unitId: 'none',
    unitLabel: '',
    purchasePrice: '0',
    salePrice: '0',
    taxRate: '0',
    minStock: '5',
    isActive: true,
  })
  const [deletingProduct, setDeletingProduct] = useState<Product | null>(null)
  const [deleting, setDeleting] = useState(false)
  const { toast } = useToast()

  // ══════════════════════════════════════════
  // ★ v9.3: بررسی بارکد تکراری به صورت خودکار
  // ══════════════════════════════════════════
  useEffect(() => {
    // بررسی بارکد در فرم ایجاد
    if (!addForm.barcode || addForm.barcode.trim() === '') {
      setAddBarcodeError('')
      setAddBarcodeIsDuplicate(false)
    } else if (addForm.generateBarcode) {
      // بارکد تولیدشده خودکار نیازی به چک ندارد
      setAddBarcodeError('')
      setAddBarcodeIsDuplicate(false)
    } else {
      const trimmed = addForm.barcode.trim()
      const duplicate = allProducts.find(
        (p) => p.barcode && p.barcode.trim() === trimmed
      )
      if (duplicate) {
        setAddBarcodeIsDuplicate(true)
        setAddBarcodeError(
          `⚠️ این بارکد قبلاً برای کالای «${duplicate.name}» استفاده شده است`
        )
      } else {
        setAddBarcodeIsDuplicate(false)
        setAddBarcodeError('')
      }
    }
  }, [addForm.barcode, addForm.generateBarcode, allProducts])

  useEffect(() => {
    // بررسی بارکد در فرم ویرایش
    if (!editForm.barcode || editForm.barcode.trim() === '') {
      setEditBarcodeError('')
      setEditBarcodeIsDuplicate(false)
    } else {
      const trimmed = editForm.barcode.trim()
      // بررسی تکراری بودن (به جز خود کالا)
      const duplicate = allProducts.find(
        (p) => p.id !== editForm.id && p.barcode && p.barcode.trim() === trimmed
      )
      if (duplicate) {
        setEditBarcodeIsDuplicate(true)
        setEditBarcodeError(
          `⚠️ این بارکد قبلاً برای کالای «${duplicate.name}» استفاده شده است`
        )
      } else {
        setEditBarcodeIsDuplicate(false)
        setEditBarcodeError('')
      }
    }
  }, [editForm.barcode, editForm.id, allProducts])

  // ══════════════════════════════════════════
  // ★ Load Products
  // ══════════════════════════════════════════
  const loadProducts = useCallback(
    async (pageNum: number = 1, searchTerm: string = '') => {
      setLoading(true)
      const trulyOnline = isOnline && navigator.onLine

      if (!trulyOnline) {
        console.log('[Products] 📡 آفلاین — بارگذاری از cache...')
        try {
          const { getCachedProducts } = await import('@/lib/offline-db')
          let cached: any[] = await getCachedProducts()
          if (searchTerm) {
            const q = searchTerm.toLowerCase()
            cached = cached.filter(
              (p: any) =>
                p.name?.toLowerCase().includes(q) ||
                p.code?.toLowerCase().includes(q) ||
                p.barcode?.includes(searchTerm)
            )
          }
          if (selectedCategory && selectedCategory !== 'all') {
            cached = cached.filter((p: any) => p.categoryId === selectedCategory)
          }
          const pageSize = 12
          const totalItems = cached.length
          const totalPagesCalc = Math.max(1, Math.ceil(totalItems / pageSize))
          const start = (pageNum - 1) * pageSize
          const pageItems = cached.slice(start, start + pageSize)
          setProducts(pageItems.map((p: any) => ({ ...p, _isOffline: true })))
          setTotal(totalItems)
          setTotalPages(totalPagesCalc)
          setPage(pageNum)
          if (!isOnline) {
            toast({
              title: '📡 حالت آفلاین',
              description: 'کالاها از حافظه محلی بارگذاری شدند',
              duration: 3000,
            })
          }
        } catch (err) {
          console.error('[Products] خطا در بارگذاری cache:', err)
          setProducts([])
        }
        setLoading(false)
        return
      }

      try {
        const params = new URLSearchParams({
          page: String(pageNum),
          limit: '12',
          sort: 'recent',
        })
        if (searchTerm) params.set('search', searchTerm)
        if (selectedCategory && selectedCategory !== 'all')
          params.set('categoryId', selectedCategory)

        const res = await fetch(`/api/products?${params.toString()}`, {
          headers: getAuthHeaders(),
        })
        const json = await res.json()
        if (json.success) {
          setProducts(json.data || [])
          if (json.pagination) {
            setTotalPages(json.pagination.totalPages)
            setTotal(json.pagination.total)
            setPage(json.pagination.page)
          }
          try {
            const { cacheProducts } = await import('@/lib/offline-db')
            await cacheProducts(json.data || [])
          } catch {}
        } else {
          setProducts([])
        }
      } catch (error) {
        console.error('Error loading products:', error)
        try {
          const { getCachedProducts } = await import('@/lib/offline-db')
          const cached = await getCachedProducts()
          if (cached.length > 0) {
            setProducts(cached.slice(0, 12).map((p: any) => ({ ...p, _isOffline: true })))
            setTotal(cached.length)
          } else {
            setProducts([])
          }
        } catch {
          setProducts([])
        }
      }
      setLoading(false)
    },
    [selectedCategory, toast, isOnline]
  )

  const loadAllProducts = useCallback(async () => {
    const trulyOnline = isOnline && navigator.onLine
    if (!trulyOnline) {
      try {
        const { getCachedProducts } = await import('@/lib/offline-db')
        const cached = await getCachedProducts()
        setAllProducts(cached)
      } catch {}
      return
    }
    try {
      const res = await fetch(`/api/products?page=1&limit=1000&sort=recent`, {
        headers: getAuthHeaders(),
      })
      const json = await res.json()
      if (json.success) {
        const all = json.data || []
        setAllProducts(all)
        try {
          const { cacheProducts } = await import('@/lib/offline-db')
          await cacheProducts(all)
        } catch {}
      }
    } catch (error) {
      console.error('Error loading all products:', error)
    }
  }, [isOnline])

  useEffect(() => {
    const timer = setTimeout(() => {
      if (searchInput !== search) {
        setSearch(searchInput)
        loadProducts(1, searchInput)
      }
    }, 400)
    return () => clearTimeout(timer)
  }, [searchInput, search, loadProducts])

  const loadCategories = useCallback(async () => {
    const trulyOnline = isOnline && navigator.onLine
    if (!trulyOnline) {
      try {
        const { getCachedCategories } = await import('@/lib/offline-db')
        const cached = await getCachedCategories()
        setCategories(cached.filter((c: any) => c.isActive !== false))
      } catch {
        setCategories([])
      }
      return
    }
    try {
      const res = await fetch(`/api/categories?tenantId=${tenantId}`, {
        headers: getAuthHeaders(),
      })
      const json = await res.json()
      if (json.success) {
        const cats = json.data.categories || json.data
        const activeCats = Array.isArray(cats) ? cats.filter((c: Category) => c.isActive) : []
        setCategories(activeCats)
        try {
          const { cacheCategories } = await import('@/lib/offline-db')
          await cacheCategories(Array.isArray(cats) ? cats : [])
        } catch {}
      }
    } catch (error) {
      console.error('Error loading categories:', error)
      try {
        const { getCachedCategories } = await import('@/lib/offline-db')
        const cached = await getCachedCategories()
        setCategories(cached.filter((c: any) => c.isActive !== false))
      } catch {
        setCategories([])
      }
    }
  }, [tenantId, isOnline])

  const loadUnits = useCallback(async () => {
    const trulyOnline = isOnline && navigator.onLine
    if (!trulyOnline) {
      try {
        const cached = localStorage.getItem('cached_units')
        if (cached) {
          const data = JSON.parse(cached)
          setUnits(data.units || [])
        } else {
          setUnits([])
        }
      } catch {
        setUnits([])
      }
      return
    }
    try {
      const res = await fetch(`/api/units?tenantId=${tenantId}`, {
        headers: getAuthHeaders(),
      })
      const json = await res.json()
      if (json.success) {
        const uList = json.data.units || json.data
        const unitsArr = Array.isArray(uList) ? uList : []
        setUnits(unitsArr)
        try {
          localStorage.setItem('cached_units', JSON.stringify({
            units: unitsArr,
            cachedAt: new Date().toISOString(),
          }))
        } catch {}
      }
    } catch (error) {
      console.error('Error loading units:', error)
      try {
        const cached = localStorage.getItem('cached_units')
        if (cached) {
          const data = JSON.parse(cached)
          setUnits(data.units || [])
        } else {
          setUnits([])
        }
      } catch {
        setUnits([])
      }
    }
  }, [tenantId, isOnline])

  const loadPlanLimits = useCallback(async () => {
    const trulyOnline = isOnline && navigator.onLine
    if (!trulyOnline) {
      setPlanLimits(null)
      return
    }
    try {
      const res = await fetch(
        `/api/plan-limits?tenantId=${tenantId}&feature=products`,
        { headers: getAuthHeaders() }
      )
      const json = await res.json()
      setPlanLimits(json.success ? json.data : null)
    } catch (error) {
      console.error('Error loading plan limits:', error)
      setPlanLimits(null)
    }
  }, [tenantId, isOnline])

  useEffect(() => {
    loadProducts(1, '')
    loadCategories()
    loadUnits()
    loadPlanLimits()
    loadAllProducts()
  }, [loadProducts, loadCategories, loadUnits, loadPlanLimits, loadAllProducts])

  useEffect(() => {
    const handleOnline = () => {
      console.log('[Products] 🟢 آنلاین شد — همگام‌سازی...')
      loadProducts(1, search)
      loadCategories()
      loadUnits()
      loadPlanLimits()
      loadAllProducts()
      import('@/lib/sync-engine').then(({ syncEngine }) => {
        syncEngine.init()
        syncEngine.sync().catch(() => {})
      }).catch(() => {})
    }
    const handleOffline = () => {
      console.log('[Products] 🔴 آفلاین شد')
      toast({
        title: '📡 اتصال قطع شد',
        description: 'حالت آفلاین فعال شد',
        duration: 3000,
      })
    }
    window.addEventListener('online', handleOnline)
    window.addEventListener('offline', handleOffline)
    return () => {
      window.removeEventListener('online', handleOnline)
      window.removeEventListener('offline', handleOffline)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loadProducts, loadCategories, loadUnits, loadPlanLimits, loadAllProducts, search])

  useEffect(() => {
    setPage(1)
    loadProducts(1, search)
  }, [selectedCategory, loadProducts, search])

  const triggerSync = useCallback(async () => {
    if (isSyncing || !isOnline) return
    setIsSyncing(true)
    try {
      const { syncEngine } = await import('@/lib/sync-engine')
      syncEngine.init()
      await syncEngine.sync()
      await loadProducts(page, search)
      await loadAllProducts()
    } catch (err) {
      console.error('[Products] Manual sync failed:', err)
      toast({ title: 'خطا در همگام‌سازی', variant: 'destructive' })
    }
    setIsSyncing(false)
  }, [isSyncing, isOnline, loadProducts, loadAllProducts, page, search, toast])

  const fetchNextCode = useCallback(async () => {
    setGeneratingCode(true)
    try {
      const res = await fetch('/api/products?action=nextCode', {
        headers: getAuthHeaders(),
      })
      const json = await res.json()
      if (json.success && json.data?.code) {
        setAddForm((prev) => ({ ...prev, code: json.data.code }))
      }
    } catch (error) {
      console.error('Error fetching next code:', error)
      const count = products.length
      const fallbackCode = `PRD-${(count + 1).toString().padStart(6, '0')}`
      setAddForm((prev) => ({ ...prev, code: fallbackCode }))
    }
    setGeneratingCode(false)
  }, [products.length])

  const handleOpenAddDialog = useCallback(async () => {
    setAddForm(INITIAL_ADD_FORM)
    setAddBarcodeError('')
    setAddBarcodeIsDuplicate(false)
    setAddDialogOpen(true)
    await fetchNextCode()
  }, [fetchNextCode])

  const handleGenerateBarcodeToggle = (checked: boolean) => {
    if (checked) {
      const timestamp = Date.now().toString().slice(-4)
      const random = Math.floor(Math.random() * 100)
        .toString()
        .padStart(2, '0')
      const barcode12 = '629123' + timestamp + random

      let sum = 0
      for (let i = 0; i < 12; i++) {
        const digit = parseInt(barcode12[i])
        const multiplier = i % 2 === 0 ? 1 : 3
        sum += digit * multiplier
      }
      const checkDigit = (10 - (sum % 10)) % 10
      const barcodeValue = barcode12 + checkDigit.toString()

      setAddForm((prev) => ({
        ...prev,
        generateBarcode: true,
        barcode: barcodeValue,
      }))
    } else {
      setAddForm((prev) => ({
        ...prev,
        generateBarcode: false,
        barcode: '',
      }))
    }
  }

  // ══════════════════════════════════════════
  // ★ v9.3: handleAddProduct با validation کامل
  // ══════════════════════════════════════════
  const handleAddProduct = async () => {
    // ★ Validation 1: نام کالا
    if (!addForm.name.trim()) {
      toast({ title: 'خطا', description: 'نام کالا الزامی است', variant: 'destructive' })
      return
    }
    // ★ Validation 2: کد کالا
    if (!addForm.code.trim()) {
      toast({ title: 'خطا', description: 'کد کالا الزامی است', variant: 'destructive' })
      return
    }
    // ★ Validation 3: بارکد تکراری
    if (addBarcodeIsDuplicate) {
      toast({
        title: 'خطا',
        description: 'بارکد وارد شده تکراری است. لطفاً بارکد دیگری وارد کنید.',
        variant: 'destructive',
      })
      return
    }
    // ★ Validation 4: دسته‌بندی اجباری
    if (!addForm.categoryId || addForm.categoryId === 'none') {
      toast({
        title: 'خطا',
        description: 'انتخاب دسته‌بندی کالا الزامی است',
        variant: 'destructive',
      })
      return
    }
    // ★ Validation 5: واحد اجباری
    if (!addForm.unitId || addForm.unitId === 'none') {
      toast({
        title: 'خطا',
        description: 'انتخاب واحد کالا الزامی است',
        variant: 'destructive',
      })
      return
    }

    const trulyOnline = isOnline && navigator.onLine

    if (!trulyOnline) {
      setSubmitting(true)
      try {
        const { addToSyncQueue } = await import('@/lib/offline-db')
        const body = {
          ...addForm,
          tenantId,
          purchasePrice: parsePersianNumber(addForm.purchasePrice),
          salePrice: parsePersianNumber(addForm.salePrice),
          taxRate: parsePersianNumber(addForm.taxRate),
          currentStock: 0,
          minStock: parsePersianNumber(addForm.minStock),
          categoryId: addForm.categoryId === 'none' ? null : addForm.categoryId,
          unitId: addForm.unitId === 'none' ? null : addForm.unitId,
          generateBarcode: addForm.generateBarcode && !addForm.barcode,
          barcode: addForm.barcode || null,
        }
        await addToSyncQueue('product', { method: 'POST', url: '/api/products', body })
        const tempProduct: Product = {
          id: `offline-${Date.now()}`,
          code: addForm.code,
          barcode: addForm.barcode || null,
          name: addForm.name,
          categoryId: addForm.categoryId === 'none' ? null : addForm.categoryId,
          unitId: addForm.unitId === 'none' ? null : addForm.unitId,
          purchasePrice: parsePersianNumber(addForm.purchasePrice),
          salePrice: parsePersianNumber(addForm.salePrice),
          taxRate: parsePersianNumber(addForm.taxRate),
          currentStock: 0,
          minStock: parsePersianNumber(addForm.minStock),
          isActive: addForm.isActive,
          createdAt: new Date().toISOString(),
          _isOffline: true,
          _offlineAction: 'create',
          _syncStatus: 'pending',
        }
        setProducts((prev) => [tempProduct, ...prev])
        setAllProducts((prev) => [tempProduct, ...prev])
        toast({
          title: '✓ در صف ذخیره شد',
          description: `کالای «${addForm.name}» با موفقیت ثبت شد. می‌توانید کالای بعدی را وارد کنید.`,
          duration: 4000,
        })

        // ★ v9.3: مودال را نمی‌بندیم! فقط فیلدهای منحصر به فرد را پاک می‌کنیم
        // تا کاربر بتواند سریع کالای بعدی را ثبت کند
        const newCode = `PRD-${(products.length + 2).toString().padStart(6, '0')}`
        setAddForm((prev) => ({
          ...prev,
          name: '',
          code: newCode,
          barcode: '',
          generateBarcode: false,
          // دسته‌بندی، واحد، قیمت‌ها و حداقل موجودی حفظ می‌شوند
        }))
        setAddBarcodeError('')
        setAddBarcodeIsDuplicate(false)
        // دریافت کد جدید از سرور در پس‌زمینه
        fetchNextCode()
      } catch (error: any) {
        toast({ title: 'خطا', description: error?.message, variant: 'destructive' })
      }
      setSubmitting(false)
      return
    }

    setSubmitting(true)
    try {
      const body = {
        ...addForm,
        tenantId,
        purchasePrice: parsePersianNumber(addForm.purchasePrice),
        salePrice: parsePersianNumber(addForm.salePrice),
        taxRate: parsePersianNumber(addForm.taxRate),
        currentStock: 0,
        minStock: parsePersianNumber(addForm.minStock),
        categoryId: addForm.categoryId === 'none' ? null : addForm.categoryId,
        unitId: addForm.unitId === 'none' ? null : addForm.unitId,
        generateBarcode: addForm.generateBarcode && !addForm.barcode,
        barcode: addForm.barcode || null,
      }

      const res = await fetch('/api/products', {
        method: 'POST',
        headers: getAuthHeaders(),
        body: JSON.stringify(body),
      })
      const json = await res.json()
      if (json.success) {
        toast({
          title: '✓ کالا ایجاد شد',
          description: json.data.barcode
            ? `کالای «${addForm.name}» با بارکد ${json.data.barcode} ثبت شد. می‌توانید کالای بعدی را وارد کنید.`
            : `کالای «${addForm.name}» با موفقیت ثبت شد. می‌توانید کالای بعدی را وارد کنید.`,
        })

        // ★ v9.3: مودال را نمی‌بندیم! فقط فیلدهای منحصر به فرد را پاک می‌کنیم
        setAddForm((prev) => ({
          ...prev,
          name: '',
          code: '',
          barcode: '',
          generateBarcode: false,
          // دسته‌بندی، واحد، قیمت‌ها و حداقل موجودی حفظ می‌شوند
        }))
        setAddBarcodeError('')
        setAddBarcodeIsDuplicate(false)
        // بارگذاری مجدد لیست‌ها و دریافت کد جدید
        loadProducts(page, search)
        loadAllProducts()
        loadPlanLimits()
        fetchNextCode()
      } else {
        toast({ title: 'خطا', description: json.error, variant: 'destructive' })
      }
    } catch (error: any) {
      toast({ title: 'خطا', description: error?.message, variant: 'destructive' })
    }
    setSubmitting(false)
  }
    // ══════════════════════════════════════════
  // ★ v9.3: handleEditProduct با validation کامل
  // ══════════════════════════════════════════
  const handleEditProduct = async () => {
    // ★ Validation 1: نام و کد
    if (!editForm.name.trim() || !editForm.code.trim()) {
      toast({ title: 'خطا', description: 'نام و کد کالا الزامی است', variant: 'destructive' })
      return
    }
    // ★ Validation 2: بارکد تکراری
    if (editBarcodeIsDuplicate) {
      toast({
        title: 'خطا',
        description: 'بارکد وارد شده تکراری است. لطفاً بارکد دیگری وارد کنید.',
        variant: 'destructive',
      })
      return
    }
    // ★ Validation 3: دسته‌بندی اجباری
    if (!editForm.categoryId || editForm.categoryId === 'none') {
      toast({
        title: 'خطا',
        description: 'انتخاب دسته‌بندی کالا الزامی است',
        variant: 'destructive',
      })
      return
    }
    // ★ Validation 4: واحد اجباری
    if (!editForm.unitId || editForm.unitId === 'none') {
      toast({
        title: 'خطا',
        description: 'انتخاب واحد کالا الزامی است',
        variant: 'destructive',
      })
      return
    }

    const trulyOnline = isOnline && navigator.onLine

    if (!trulyOnline) {
      setSubmitting(true)
      try {
        const { addToSyncQueue } = await import('@/lib/offline-db')
        const body = {
          id: editForm.id,
          tenantId,
          name: editForm.name,
          code: editForm.code,
          barcode: editForm.barcode || null,
          categoryId: editForm.categoryId === 'none' ? null : editForm.categoryId,
          unitId: editForm.unitId === 'none' ? null : editForm.unitId,
          unitLabel: editForm.unitLabel,
          purchasePrice: parsePersianNumber(editForm.purchasePrice),
          salePrice: parsePersianNumber(editForm.salePrice),
          taxRate: parsePersianNumber(editForm.taxRate),
          minStock: parsePersianNumber(editForm.minStock),
          isActive: editForm.isActive,
        }
        await addToSyncQueue('product', { method: 'PUT', url: '/api/products', body })
        setProducts((prev) =>
          prev.map((p) =>
            p.id === editForm.id
              ? {
                  ...p,
                  name: editForm.name,
                  code: editForm.code,
                  barcode: editForm.barcode || null,
                  categoryId: editForm.categoryId === 'none' ? null : editForm.categoryId,
                  unitId: editForm.unitId === 'none' ? null : editForm.unitId,
                  purchasePrice: parsePersianNumber(editForm.purchasePrice),
                  salePrice: parsePersianNumber(editForm.salePrice),
                  taxRate: parsePersianNumber(editForm.taxRate),
                  minStock: parsePersianNumber(editForm.minStock),
                  isActive: editForm.isActive,
                  _isOffline: true,
                  _offlineAction: 'update',
                  _syncStatus: 'pending',
                }
              : p
          )
        )
        toast({
          title: '✓ در صف بروزرسانی قرار گرفت',
          description: 'تغییرات پس از اتصال اعمال می‌شود',
          duration: 4000,
        })
        // ★ v9.3: در حالت ویرایش، مودال بسته می‌شود
        setEditDialogOpen(false)
      } catch (error: any) {
        toast({ title: 'خطا', description: error?.message, variant: 'destructive' })
      }
      setSubmitting(false)
      return
    }

    setSubmitting(true)
    try {
      const body = {
        id: editForm.id,
        tenantId,
        name: editForm.name,
        code: editForm.code,
        barcode: editForm.barcode || null,
        categoryId: editForm.categoryId === 'none' ? null : editForm.categoryId,
        unitId: editForm.unitId === 'none' ? null : editForm.unitId,
        unitLabel: editForm.unitLabel,
        purchasePrice: parsePersianNumber(editForm.purchasePrice),
        salePrice: parsePersianNumber(editForm.salePrice),
        taxRate: parsePersianNumber(editForm.taxRate),
        minStock: parsePersianNumber(editForm.minStock),
        isActive: editForm.isActive,
      }
      const res = await fetch('/api/products', {
        method: 'PUT',
        headers: getAuthHeaders(),
        body: JSON.stringify(body),
      })
      const json = await res.json()
      if (json.success) {
        toast({ title: '✓ موفق', description: 'کالا به‌روزرسانی شد' })
        // ★ v9.3: در حالت ویرایش، مودال بسته می‌شود
        setEditDialogOpen(false)
        loadProducts(page, search)
        loadAllProducts()
      } else {
        toast({ title: 'خطا', description: json.error, variant: 'destructive' })
      }
    } catch (error: any) {
      toast({ title: 'خطا', description: error?.message, variant: 'destructive' })
    }
    setSubmitting(false)
  }

  const handleDeleteProduct = async () => {
    if (!deletingProduct) return

    const trulyOnline = isOnline && navigator.onLine

    if (deletingProduct._isOffline && deletingProduct._offlineAction === 'create') {
      setDeleting(true)
      try {
        setProducts((prev) => prev.filter((p) => p.id !== deletingProduct.id))
        setAllProducts((prev) => prev.filter((p) => p.id !== deletingProduct.id))
        toast({ title: '✓ حذف شد', description: 'کالا آفلاین حذف شد' })
        setDeletingProduct(null)
      } catch (error: any) {
        toast({ title: 'خطا', description: error?.message, variant: 'destructive' })
      }
      setDeleting(false)
      return
    }

    if (!trulyOnline) {
      setDeleting(true)
      try {
        const { addToSyncQueue } = await import('@/lib/offline-db')
        await addToSyncQueue('product', {
          method: 'DELETE',
          url: `/api/products?id=${deletingProduct.id}&tenantId=${tenantId}`,
          body: {},
        })
        setProducts((prev) =>
          prev.map((p) =>
            p.id === deletingProduct.id
              ? { ...p, _isOffline: true, _offlineAction: 'delete', _syncStatus: 'pending' }
              : p
          )
        )
        setAllProducts((prev) =>
          prev.map((p) =>
            p.id === deletingProduct.id
              ? { ...p, _isOffline: true, _offlineAction: 'delete', _syncStatus: 'pending' }
              : p
          )
        )
        toast({
          title: '📡 در صف حذف قرار گرفت',
          description: 'کالا پس از اتصال از سرور حذف می‌شود',
          duration: 4000,
        })
        setDeletingProduct(null)
      } catch (error: any) {
        toast({ title: 'خطا', description: error?.message, variant: 'destructive' })
      }
      setDeleting(false)
      return
    }

    setDeleting(true)
    try {
      const res = await fetch(
        `/api/products?id=${deletingProduct.id}&tenantId=${tenantId}`,
        { method: 'DELETE', headers: getAuthHeaders() }
      )
      const json = await res.json()
      if (json.success) {
        toast({ title: 'موفق', description: json.message })
        setProducts((prev) => prev.filter((p) => p.id !== deletingProduct.id))
        setAllProducts((prev) => prev.filter((p) => p.id !== deletingProduct.id))
        setDeletingProduct(null)
        loadProducts(page, search)
        loadAllProducts()
        loadPlanLimits()
      } else {
        toast({ title: 'خطا', description: json.error, variant: 'destructive' })
      }
    } catch (error: any) {
      toast({ title: 'خطا', description: error?.message, variant: 'destructive' })
    }
    setDeleting(false)
  }

  const openEditDialog = (product: Product) => {
    const unitLabel = product.unit ? getUnitLabel(product.unit) : product.unitLabel || ''

    setEditForm({
      id: product.id,
      name: product.name,
      code: product.code,
      barcode: product.barcode || '',
      categoryId: product.categoryId || 'none',
      unitId: product.unitId || 'none',
      unitLabel,
      purchasePrice: String(product.purchasePrice),
      salePrice: String(product.salePrice),
      taxRate: String(product.taxRate),
      minStock: String(product.minStock),
      isActive: product.isActive,
    })
    setEditBarcodeError('')
    setEditBarcodeIsDuplicate(false)
    setEditDialogOpen(true)
  }

  // ══════════════════════════
  // Computed Values
  // ══════════════════════════
  const productsWithBarcodeCount = allProducts.filter(
    (p) => isAutoGeneratedBarcode(p.barcode)
  ).length

  const offlineCount = useMemo(
    () => products.filter((p) => p._isOffline && p._offlineAction !== 'delete').length,
    [products]
  )

  // ★ محاسبه مجموع ارزش کل موجودی انبار (از همه کالاات — ثابت با تغییر صفحه)
  const totalInventoryValue = useMemo(() => {
    return allProducts.reduce((sum, p) =>
      sum + calculateTotalValue(p.currentStock, p.salePrice), 0
    )
  }, [allProducts])

  // ★ تعداد کل اقلام موجود در انبار
  const totalInventoryItems = useMemo(() => {
    return allProducts.reduce((sum, p) => sum + (p.currentStock || 0), 0)
  }, [allProducts])

  // ★ تعداد کالاهایی که موجودی دارند
  const productsWithStockCount = useMemo(() => {
    return allProducts.filter(p => (p.currentStock || 0) > 0).length
  }, [allProducts])

  // ══════════════════════════════════════════════════════════════
  // ★ Render
  // ══════════════════════════════════════════════════════════════
  return (
    <div className="space-y-3 sm:space-y-4" dir="rtl">
      {/* ★ Header با ارزش کل انبار */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-2">
          <div className="w-9 h-9 rounded-xl bg-emerald-100 flex items-center justify-center shrink-0">
            <Package className="w-5 h-5 text-emerald-600" />
          </div>
          <div>
            <h1 className="text-base sm:text-lg font-bold text-gray-900">کالاها</h1>
            <div className="flex items-center gap-2 flex-wrap mt-0.5">
              <p className="text-xs text-gray-500">{toFaNum(total)} کالا</p>
              {totalInventoryValue > 0 && (
                <>
                  <span className="text-gray-300">•</span>
                  <div className="flex items-center gap-1">
                    <TrendingUp className="w-3 h-3 text-emerald-600" />
                    <p className="text-xs text-emerald-700 font-medium">
                      ارزش کل: {formatPrice(totalInventoryValue)}
                    </p>
                  </div>
                </>
              )}
            </div>
          </div>
        </div>
        <div className="flex items-center gap-2 flex-wrap">
          {!isOnline && (
            <Badge variant="outline" className="gap-1 text-[10px] border-amber-300 text-amber-700 bg-amber-50 px-1.5 py-0.5">
              <WifiOff className="w-2.5 h-2.5" />
              <span className="hidden sm:inline">آفلاین</span>
            </Badge>
          )}

          {offlineCount > 0 && (
            <Badge
              variant="outline"
              className="gap-1 text-[10px] border-blue-300 text-blue-700 bg-blue-50 cursor-pointer px-1.5 py-0.5"
              onClick={() => isOnline && triggerSync()}
              title="کلیک کنید تا همگام‌سازی شود"
            >
              {isSyncing ? (
                <Loader2 className="w-2.5 h-2.5 animate-spin" />
              ) : (
                <Upload className="w-2.5 h-2.5" />
              )}
              <span className="hidden sm:inline">{toFaNum(offlineCount)} در انتظار</span>
              <span className="sm:hidden">{toFaNum(offlineCount)}</span>
            </Badge>
          )}

          {isOnline && offlineCount > 0 && !isSyncing && (
            <Button
              variant="outline"
              size="sm"
              onClick={triggerSync}
              className="text-xs border-blue-300 text-blue-600 hover:bg-blue-50 h-8 sm:h-9 px-2 sm:px-3 gap-1"
            >
              <RefreshCw className="w-3 h-3 sm:w-3.5 sm:h-3.5" />
              <span className="hidden sm:inline">همگام‌سازی</span>
            </Button>
          )}

          <Button
            variant="outline"
            size="sm"
            onClick={() => {
              loadAllProducts()
              setPrintModalOpen(true)
            }}
            className="flex-1 sm:flex-none gap-1.5 text-xs border-emerald-300 text-emerald-700 hover:bg-emerald-50 h-8 sm:h-9"
          >
            <Printer className="w-3.5 h-3.5" />
            <span className="hidden xs:inline sm:inline">چاپ بارکد</span>
            {productsWithBarcodeCount > 0 && (
              <span className="bg-emerald-100 text-emerald-700 text-[10px] px-1.5 py-0.5 rounded-full">
                {toFaNum(productsWithBarcodeCount)}
              </span>
            )}
          </Button>

          <Button
            onClick={handleOpenAddDialog}
            className="flex-1 sm:flex-none gap-1.5 bg-emerald-600 hover:bg-emerald-700 text-xs h-8 sm:h-9"
            disabled={planLimits ? !planLimits.canAdd : false}
          >
            <Plus className="w-4 h-4" />
            <span>کالا جدید</span>
          </Button>
        </div>
      </div>

      {!isOnline && offlineCount > 0 && (
        <div className="flex items-center gap-2 bg-amber-50 border border-amber-200 rounded-lg px-3 py-2">
          <CloudOff className="w-4 h-4 text-amber-600 shrink-0" />
          <div className="flex-1 text-xs text-amber-700">
            <span className="font-bold">{toFaNum(offlineCount)} تغییر آفلاین </span>
            <span className="hidden sm:inline">در انتظار همگام‌سازی با سرور هستند.</span>
            <span className="sm:hidden">در انتظار sync</span>
          </div>
        </div>
      )}

      {planLimits && !planLimits.canAdd && (
        <Card className="border-amber-200 bg-amber-50/50">
          <CardContent className="p-3 flex items-center gap-2">
            <AlertTriangle className="w-4 h-4 text-amber-600 flex-shrink-0" />
            <p className="text-xs text-amber-700">
              سقف پلن ({toFaNum(planLimits.maxProducts)}) تکمیل شده است.
            </p>
          </CardContent>
        </Card>
      )}

      {/* ★ Search & Filter */}
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-2">
        <div className="relative flex-1 min-w-0">
          <Search className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
          <Input
            placeholder="جستجوی کالا (نام، کد، بارکد)..."
            value={searchInput}
            onChange={(e) => setSearchInput(e.target.value)}
            className="pr-9 h-9"
          />
        </div>
        <div className="flex items-center gap-2">
          <Select value={selectedCategory} onValueChange={setSelectedCategory}>
            <SelectTrigger className="flex-1 sm:flex-none sm:w-[150px] h-9">
              <Filter className="w-3.5 h-3.5 ml-1 text-gray-400 shrink-0" />
              <SelectValue />
            </SelectTrigger>
            <SelectContent className="z-[99999]">
              <SelectItem value="all">همه دسته‌ها</SelectItem>
              {categories.map((cat) => (
                <SelectItem key={cat.id} value={cat.id}>
                  {cat.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Button
            variant="outline"
            size="sm"
            onClick={() => {
              setSearchInput('')
              setSearch('')
              loadProducts(1, '')
            }}
            className="gap-1 h-9 shrink-0 px-2.5"
          >
            <RefreshCw className="w-3.5 h-3.5" />
            <span className="hidden sm:inline">پاک کردن</span>
          </Button>
        </div>
      </div>

      {loading ? (
        <Card>
          <CardContent className="flex items-center justify-center py-12">
            <Loader2 className="w-6 h-6 animate-spin text-emerald-500" />
          </CardContent>
        </Card>
      ) : products.length === 0 ? (
        <Card>
          <CardContent className="flex flex-col items-center justify-center py-12 text-gray-400">
            <Package className="w-12 h-12 mb-2 text-gray-300" />
            <p className="text-sm">
              {search
                ? `نتیجه‌ای برای "${search}" یافت نشد`
                : 'کالای ثبت نشده است'}
            </p>
          </CardContent>
        </Card>
      ) : (
        <>
          {/* ═══ Desktop Table View با ستون ارزش موجودی ═══ */}
          <Card className="hidden lg:block">
            <CardContent className="p-0">
              <Table>
                <TableHeader>
                  <TableRow className="bg-gray-50">
                    <TableHead className="text-right text-xs">کد</TableHead>
                    <TableHead className="text-right text-xs">نام کالا</TableHead>
                    <TableHead className="text-right text-xs">بارکد</TableHead>
                    <TableHead className="text-right text-xs">دسته</TableHead>
                    <TableHead className="text-center text-xs">موجودی</TableHead>
                    <TableHead className="text-center text-xs">قیمت فروش</TableHead>
                    <TableHead className="text-center text-xs bg-emerald-50/50">ارزش موجودی</TableHead>
                    <TableHead className="text-center text-xs">واحد</TableHead>
                    <TableHead className="text-center text-xs">وضعیت</TableHead>
                    <TableHead className="text-center text-xs">عملیات</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {products.map((product) => (
                    <TableRow
                      key={product.id}
                      className={`hover:bg-emerald-50/50 ${product._isOffline ? 'bg-amber-50/40' : ''}`}
                    >
                      <TableCell className="text-xs font-mono" dir="ltr">
                        {toFaNum(product.code)}
                      </TableCell>
                      <TableCell className="text-xs font-medium">
                        <div className="flex items-center gap-1.5">
                          <span>{product.name}</span>
                          {isAutoGeneratedBarcode(product.barcode) && (
                            <span title="بارکد تولید شده با دکمه" className="inline-flex shrink-0">
                              <Barcode className="w-3 h-3 text-emerald-600" />
                            </span>
                          )}
                          {product._isOffline && (
                            <Badge
                              variant="outline"
                              className={`text-[9px] h-4 px-1 shrink-0 ${
                                product._offlineAction === 'delete'
                                  ? 'border-red-300 text-red-600 bg-red-50'
                                  : product._offlineAction === 'create'
                                  ? 'border-emerald-300 text-emerald-600 bg-emerald-50'
                                  : 'border-amber-300 text-amber-600 bg-amber-50'
                              }`}
                            >
                              {product._offlineAction === 'delete' ? 'حذف آفلاین' :
                               product._offlineAction === 'create' ? 'جدید آفلاین' :
                               'ویرایش آفلاین'}
                            </Badge>
                          )}
                        </div>
                      </TableCell>
                      <TableCell className="text-xs" dir="ltr">
                        {product.barcode ? (
                          <span className="font-mono text-gray-600 bg-gray-100 px-1.5 py-0.5 rounded text-[11px]">
                            {toFaNum(product.barcode)}
                          </span>
                        ) : (
                          <span className="text-gray-400 text-[11px]">—</span>
                        )}
                      </TableCell>
                      <TableCell className="text-xs">
                        {product.category?.name || '—'}
                      </TableCell>
                      <TableCell className="text-center">
                        <span
                          className={`text-xs font-bold ${
                            product.currentStock <= product.minStock
                              ? 'text-red-500'
                              : 'text-emerald-600'
                          }`}
                        >
                          {toFaNum(product.currentStock)}
                        </span>
                      </TableCell>
                      <TableCell className="text-center text-xs font-medium text-gray-700" dir="rtl">
                        {formatPrice(product.salePrice)}
                      </TableCell>
                      {/* ★ ستون جدید: ارزش موجودی */}
                      <TableCell className="text-center bg-emerald-50/30">
                        <StockValueBadge
                          currentStock={product.currentStock}
                          salePrice={product.salePrice}
                        />
                      </TableCell>
                      <TableCell className="text-center text-xs">
                        {product.unit
                          ? getUnitLabel(product.unit)
                          : product.unitLabel || '—'}
                      </TableCell>
                      <TableCell className="text-center">
                        <Badge
                          className={
                            product.isActive
                              ? 'bg-emerald-100 text-emerald-700'
                              : 'bg-gray-100 text-gray-500'
                          }
                        >
                          {product.isActive ? 'فعال' : 'غیرفعال'}
                        </Badge>
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center justify-center gap-1">
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => openEditDialog(product)}
                            disabled={product._offlineAction === 'delete'}
                            className="h-7 w-7 p-0 text-blue-600 hover:text-blue-700 hover:bg-blue-50 disabled:text-gray-300"
                            title="ویرایش"
                          >
                            <Edit2 className="w-3.5 h-3.5" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => setDeletingProduct(product)}
                            disabled={product._offlineAction === 'delete'}
                            className="h-7 w-7 p-0 text-red-500 hover:text-red-600 hover:bg-red-50 disabled:text-gray-300"
                            title="حذف"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>

          {/* ═══ Mobile / Tablet Card View با کارت ارزش موجودی ═══ */}
          <div className="lg:hidden grid grid-cols-1 sm:grid-cols-2 gap-2.5">
            {products.map((product) => (
              <Card
                key={product.id}
                className={`border-gray-200 ${product._isOffline ? 'border-amber-200 bg-amber-50/30' : ''}`}
              >
                <CardContent className="p-3">
                  <div className="flex items-start justify-between gap-2 mb-2">
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-1.5 mb-0.5">
                        <p className="font-bold text-sm text-gray-900 truncate">
                          {product.name}
                        </p>
                        {isAutoGeneratedBarcode(product.barcode) && (
                          <span title="بارکد تولید شده با دکمه" className="inline-flex shrink-0">
                            <Barcode className="w-3.5 h-3.5 text-emerald-600" />
                          </span>
                        )}
                      </div>
                      <p className="text-[10px] text-gray-400 font-mono mt-0.5" dir="ltr">
                        {toFaNum(product.code)}
                      </p>
                    </div>
                    <div className="flex flex-col gap-1 shrink-0">
                      <Badge
                        className={`text-[9px] ${
                          product.isActive
                            ? 'bg-emerald-100 text-emerald-700'
                            : 'bg-gray-100 text-gray-500'
                        }`}
                      >
                        {product.isActive ? 'فعال' : 'غیرفعال'}
                      </Badge>
                      {product._isOffline && (
                        <Badge
                          variant="outline"
                          className={`text-[9px] h-4 px-1 ${
                            product._offlineAction === 'delete'
                              ? 'border-red-300 text-red-600 bg-red-50'
                              : product._offlineAction === 'create'
                              ? 'border-emerald-300 text-emerald-600 bg-emerald-50'
                              : 'border-amber-300 text-amber-600 bg-amber-50'
                          }`}
                        >
                          {product._offlineAction === 'delete' ? 'حذف آفلاین' :
                           product._offlineAction === 'create' ? 'جدید آفلاین' :
                           'ویرایش آفلاین'}
                        </Badge>
                      )}
                    </div>
                  </div>

                  {product.barcode && (
                    <div className="mb-2">
                      <span
                        className="font-mono text-gray-600 bg-gray-100 px-1.5 py-0.5 rounded text-[10px]"
                        dir="ltr"
                      >
                        {toFaNum(product.barcode)}
                      </span>
                    </div>
                  )}

                  <div className="grid grid-cols-2 gap-x-3 gap-y-1.5 text-[11px] text-gray-500 border-t border-gray-100 pt-2">
                    <div className="flex items-center justify-between">
                      <span>دسته:</span>
                      <span className="text-gray-700 truncate">
                        {product.category?.name || '—'}
                      </span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span>واحد:</span>
                      <span className="text-gray-700">
                        {product.unit
                          ? getUnitLabel(product.unit)
                          : product.unitLabel || '—'}
                      </span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span>موجودی:</span>
                      <span
                        className={`font-bold ${
                          product.currentStock <= product.minStock
                            ? 'text-red-500'
                            : 'text-emerald-600'
                        }`}
                      >
                        {toFaNum(product.currentStock)}
                      </span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span>قیمت فروش:</span>
                      <span className="text-gray-700 font-medium" dir="ltr">
                        {formatPrice(product.salePrice)}
                      </span>
                    </div>
                  </div>

                  {/* ★ بخش جدید: ارزش موجودی */}
                  <StockValueCard
                    currentStock={product.currentStock}
                    salePrice={product.salePrice}
                  />

                  <div className="flex items-center justify-end gap-1 mt-2.5 pt-2 border-t border-gray-100">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => openEditDialog(product)}
                      disabled={product._offlineAction === 'delete'}
                      className="h-7 px-2 text-[10px] text-blue-600 hover:text-blue-700 hover:bg-blue-50 disabled:text-gray-300"
                    >
                      <Edit2 className="w-3 h-3 ml-1" />
                      ویرایش
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => setDeletingProduct(product)}
                      disabled={product._offlineAction === 'delete'}
                      className="h-7 px-2 text-[10px] text-red-500 hover:text-red-600 hover:bg-red-50 disabled:text-gray-300"
                    >
                      <Trash2 className="w-3 h-3 ml-1" />
                      حذف
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </>
      )}

      {!loading && products.length > 0 && (
        <div className="flex flex-col sm:flex-row items-center justify-between gap-2 px-1 sm:px-4 py-3 border-t border-gray-200">
          <p className="text-xs text-gray-500 text-center sm:text-right">
            نمایش {toFaNum((page - 1) * 12 + 1)} تا{' '}
            {toFaNum(Math.min(page * 12, total))} از {toFaNum(total)} کالا
          </p>
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              className="h-7 text-xs"
              disabled={page <= 1}
              onClick={() => loadProducts(page - 1, search)}
            >
              قبلی
            </Button>
            <span className="text-xs text-gray-600 px-2">
              صفحه {toFaNum(page)} از {toFaNum(totalPages)}
            </span>
            <Button
              variant="outline"
              size="sm"
              className="h-7 text-xs"
              disabled={page >= totalPages}
              onClick={() => loadProducts(page + 1, search)}
            >
              بعدی
            </Button>
          </div>
        </div>
      )}

      {/* ══════════════════════════════════════════════════════════ */}
      {/* ★ Add Dialog - v9.3: با preventDefault برای بیرون        */}
      {/* ══════════════════════════════════════════════════════════ */}
      <Dialog open={addDialogOpen} onOpenChange={setAddDialogOpen}>
        <DialogContent
          className="sm:max-w-[520px] w-[calc(100%-2rem)] max-h-[85vh] overflow-y-auto"
          dir="rtl"
          onPointerDownOutside={(e) => e.preventDefault()}
          onInteractOutside={(e) => e.preventDefault()}
        >
          <DialogHeader>
            <DialogTitle className="text-sm sm:text-base">کالا جدید</DialogTitle>
            <DialogDescription className="text-[11px]">
              موجودی کالا از طریق فاکتور خرید افزایش می‌یابد. فقط اطلاعات
              پایه را وارد کنید.
            </DialogDescription>
          </DialogHeader>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div className="col-span-1 sm:col-span-2">
              <Label className="text-xs">
                نام کالا <span className="text-red-500">*</span>
              </Label>
              <Input
                value={addForm.name}
                onChange={(e) =>
                  setAddForm({ ...addForm, name: e.target.value })
                }
                className="mt-1"
                placeholder="نام کالا را وارد کنید"
              />
            </div>

            <div>
              <Label className="text-xs flex items-center gap-1">
                کد کالا <span className="text-red-500">*</span>
                {generatingCode && (
                  <Loader2 className="w-3 h-3 animate-spin text-gray-400" />
                )}
              </Label>
              <div className="flex gap-1 mt-1">
                <Input
                  value={addForm.code}
                  onChange={(e) =>
                    setAddForm({ ...addForm, code: e.target.value })
                  }
                  dir="ltr"
                  className="flex-1"
                  placeholder="PRD-000001"
                />
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  className="px-2 h-9 text-[11px] whitespace-nowrap shrink-0"
                  onClick={fetchNextCode}
                  disabled={generatingCode}
                  title="تولید کد جدید"
                >
                  <Wand2 className="w-3.5 h-3.5" />
                </Button>
              </div>
              <p className="text-[10px] text-gray-400 mt-0.5">
                کد به صورت خودکار تولید شده — قابل ویرایش
              </p>
            </div>

            <div>
              <Label className="text-xs">بارکد</Label>
              <Input
                value={addForm.barcode}
                onChange={(e) =>
                  setAddForm({
                    ...addForm,
                    barcode: e.target.value,
                    generateBarcode: false,
                  })
                }
                className={`mt-1 ${addBarcodeIsDuplicate ? 'border-red-400 focus-visible:ring-red-500' : ''}`}
                dir="ltr"
                placeholder="اسکن یا وارد کنید"
                disabled={addForm.generateBarcode}
              />
              {/* ★ v9.3: نمایش خطای بارکد تکراری */}
              {addBarcodeIsDuplicate && (
                <div className="flex items-center gap-1.5 mt-1.5 p-2 bg-red-50 border border-red-200 rounded-md">
                  <AlertCircle className="w-3.5 h-3.5 text-red-500 shrink-0" />
                  <span className="text-[10px] text-red-700 font-medium">
                    {addBarcodeError}
                  </span>
                </div>
              )}
              <div className="flex items-center gap-2 mt-2 p-2 bg-emerald-50 rounded-lg border border-emerald-200">
                <Checkbox
                  id="generate-barcode"
                  checked={addForm.generateBarcode}
                  onCheckedChange={(checked) =>
                    handleGenerateBarcodeToggle(Boolean(checked))
                  }
                />
                <Label
                  htmlFor="generate-barcode"
                  className="text-[11px] text-emerald-700 cursor-pointer flex items-center gap-1"
                >
                  <Barcode className="w-3 h-3" />
                  تولید بارکد EAN-13 خودکار
                </Label>
              </div>
              {addForm.generateBarcode && addForm.barcode && (
                <div
                  className="mt-1 text-[10px] font-mono text-emerald-600 bg-emerald-50 px-2 py-1 rounded border border-emerald-200"
                  dir="ltr"
                >
                  {addForm.barcode}
                </div>
              )}
            </div>

            <div>
              {/* ★ v9.3: دسته‌بندی اجباری با asterisk */}
              <Label className="text-xs">
                دسته‌بندی <span className="text-red-500">*</span>
              </Label>
              <Select
                value={addForm.categoryId}
                onValueChange={(v) =>
                  setAddForm({ ...addForm, categoryId: v })
                }
              >
                <SelectTrigger className={`mt-1 h-9 text-xs ${!addForm.categoryId || addForm.categoryId === 'none' ? 'border-dashed' : ''}`}>
                  <SelectValue placeholder="انتخاب دسته (الزامی)" />
                </SelectTrigger>
                <SelectContent className="z-[99999]">
                  <SelectItem value="none">— انتخاب کنید —</SelectItem>
                  {categories.map((cat) => (
                    <SelectItem key={cat.id} value={cat.id}>
                      {cat.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {(!addForm.categoryId || addForm.categoryId === 'none') && (
                <p className="text-[10px] text-amber-600 mt-0.5">
                  انتخاب دسته‌بندی الزامی است
                </p>
              )}
            </div>

            <div>
              {/* ★ v9.3: واحد اجباری با asterisk */}
              <Label className="text-xs">
                واحد <span className="text-red-500">*</span>
              </Label>
              <Select
                value={addForm.unitId}
                onValueChange={(v) => setAddForm({ ...addForm, unitId: v })}
              >
                <SelectTrigger className={`mt-1 h-9 text-xs ${!addForm.unitId || addForm.unitId === 'none' ? 'border-dashed' : ''}`}>
                  <SelectValue placeholder="انتخاب واحد (الزامی)" />
                </SelectTrigger>
                <SelectContent className="z-[99999] max-h-[200px] overflow-y-auto">
                  <SelectItem value="none">— انتخاب کنید —</SelectItem>
                  {sortUnits(units).map((u) => (
                    <SelectItem key={u.id} value={u.id}>
                      {getUnitLabel(u)}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {(!addForm.unitId || addForm.unitId === 'none') && (
                <p className="text-[10px] text-amber-600 mt-0.5">
                  انتخاب واحد الزامی است
                </p>
              )}
            </div>

            <div>
              <Label className="text-xs">قیمت خرید (ریال)</Label>
              <Input
                type="text"
                inputMode="numeric"
                value={formatToPersianWithCommas(addForm.purchasePrice)}
                onChange={(e) =>
                  setAddForm({ ...addForm, purchasePrice: formatToPersianWithCommas(e.target.value) })
                }
                className="mt-1"
                dir="ltr"
              />
            </div>

            <div>
              <Label className="text-xs">قیمت فروش (ریال)</Label>
              <Input
                type="text"
                inputMode="numeric"
                value={formatToPersianWithCommas(addForm.salePrice)}
                onChange={(e) =>
                  setAddForm({ ...addForm, salePrice: formatToPersianWithCommas(e.target.value) })
                }
                className="mt-1"
                dir="ltr"
              />
            </div>

            <div>
              <Label className="text-xs">درصد مالیات (اختیاری)</Label>
              <Input
                type="text"
                inputMode="numeric"
                value={formatToPersianWithCommas(addForm.taxRate)}
                onChange={(e) =>
                  setAddForm({ ...addForm, taxRate: formatToPersianWithCommas(e.target.value) })
                }
                className="mt-1"
                dir="ltr"
              />
            </div>

            <div>
              <Label className="text-xs">حداقل موجودی هشدار</Label>
              <Input
                type="text"
                inputMode="numeric"
                value={formatToPersianWithCommas(addForm.minStock)}
                onChange={(e) =>
                  setAddForm({ ...addForm, minStock: formatToPersianWithCommas(e.target.value) })
                }
                className="mt-1"
                dir="ltr"
                placeholder="۵"
              />
            </div>

            <div className="flex items-center justify-between col-span-1 sm:col-span-2 rounded-lg border border-gray-100 bg-gray-50 px-3 py-2.5">
              <div className="flex flex-col">
                <Label className="text-xs">وضعیت فعال</Label>
                <span className="text-[10px] text-gray-400 mt-0.5">
                  {addForm.isActive ? 'این کالا در فروشگاه نمایش داده می‌شود' : 'این کالا مخفی خواهد بود'}
                </span>
              </div>
              <div className="flex items-center gap-2">
                <span className={`text-xs font-medium transition-colors ${
                  addForm.isActive ? 'text-blue-600' : 'text-gray-400'
                }`}>
                  {addForm.isActive ? 'فعال' : 'غیرفعال'}
                </span>
                <CustomSwitch checked={addForm.isActive} onCheckedChange={(v) => setAddForm({ ...addForm, isActive: v })} />
              </div>
            </div>
          </div>

          <DialogFooter className="gap-2 sm:gap-0">
            <Button variant="outline" onClick={() => setAddDialogOpen(false)} className="h-9">
              انصراف
            </Button>
            <Button
              onClick={handleAddProduct}
              disabled={submitting || addBarcodeIsDuplicate}
              className={`h-9 gap-2 ${!isOnline ? 'bg-amber-600 hover:bg-amber-700' : 'bg-emerald-600 hover:bg-emerald-700'} ${(submitting || addBarcodeIsDuplicate) ? 'opacity-50 cursor-not-allowed' : ''}`}
            >
              {submitting ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : !isOnline ? (
                <CloudOff className="w-4 h-4" />
              ) : (
                <Plus className="w-4 h-4" />
              )}
              {!isOnline ? 'ذخیره آفلاین و ادامه' : 'ایجاد کالا و ادامه'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ══════════════════════════════════════════════════════════ */}
      {/* ★ Edit Dialog - v9.3: با preventDefault برای بیرون       */}

      <Dialog open={editDialogOpen} onOpenChange={setEditDialogOpen}>
        <DialogContent
          className="sm:max-w-[520px] w-[calc(100%-2rem)] max-h-[85vh] overflow-y-auto"
          dir="rtl"
          onPointerDownOutside={(e) => e.preventDefault()}
          onInteractOutside={(e) => e.preventDefault()}
        >
          <DialogHeader>
            <DialogTitle className="text-sm sm:text-base">ویرایش کالا</DialogTitle>
            <DialogDescription className="text-[11px]">
              موجودی کالا فقط از طریق فاکتور خرید/فروش تغییر می‌کند.
            </DialogDescription>
          </DialogHeader>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <Label className="text-xs">
              نام کالا <span className="text-red-500">*</span>
              </Label>
              <Input
                value={editForm.name}
                onChange={(e) =>
                  setEditForm({ ...editForm, name: e.target.value })
                }
                className="mt-1"
              />
            </div>

            <div>
              <Label className="text-xs">
                کد <span className="text-red-500">*</span>
              </Label>
              <Input
                value={editForm.code}
                onChange={(e) =>
                  setEditForm({ ...editForm, code: e.target.value })
                }
                className="mt-1"
                dir="ltr"
              />
            </div>

            <div className="col-span-1 sm:col-span-2">
              <Label className="text-xs">بارکد</Label>
              <Input
                value={editForm.barcode}
                onChange={(e) =>
                  setEditForm({ ...editForm, barcode: e.target.value })
                }
                className={`mt-1 ${editBarcodeIsDuplicate ? 'border-red-400 focus-visible:ring-red-500' : ''}`}
                dir="ltr"
                placeholder="اسکن یا دستی وارد کنید"
              />
              {/* ★ v9.3: نمایش خطای بارکد تکراری */}
              {editBarcodeIsDuplicate && (
                <div className="flex items-center gap-1.5 mt-1.5 p-2 bg-red-50 border border-red-200 rounded-md">
                  <AlertCircle className="w-3.5 h-3.5 text-red-500 shrink-0" />
                  <span className="text-[10px] text-red-700 font-medium">
                    {editBarcodeError}
                  </span>
                </div>
              )}
            </div>

            <div>
              {/* ★ v9.3: دسته‌بندی اجباری */}
              <Label className="text-xs">
                دسته‌بندی <span className="text-red-500">*</span>
              </Label>
              <Select
                value={editForm.categoryId}
                onValueChange={(v) =>
                  setEditForm({ ...editForm, categoryId: v })
                }
              >
                <SelectTrigger className={`mt-1 h-9 text-xs ${!editForm.categoryId || editForm.categoryId === 'none' ? 'border-dashed' : ''}`}>
                  <SelectValue placeholder="انتخاب دسته (الزامی)" />
                </SelectTrigger>
                <SelectContent className="z-[99999]">
                  <SelectItem value="none">— انتخاب کنید —</SelectItem>
                  {categories.map((cat) => (
                    <SelectItem key={cat.id} value={cat.id}>
                      {cat.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {(!editForm.categoryId || editForm.categoryId === 'none') && (
                <p className="text-[10px] text-amber-600 mt-0.5">
                  انتخاب دسته‌بندی الزامی است
                </p>
              )}
            </div>

            <div>
              {/* ★ v9.3: واحد اجباری */}
              <Label className="text-xs">
                واحد <span className="text-red-500">*</span>
              </Label>
              <Select
                value={editForm.unitId}
                onValueChange={(v) => setEditForm({ ...editForm, unitId: v })}
              >
                <SelectTrigger className={`mt-1 h-9 text-xs ${!editForm.unitId || editForm.unitId === 'none' ? 'border-dashed' : ''}`}>
                  <SelectValue placeholder="انتخاب واحد (الزامی)" />
                </SelectTrigger>
                <SelectContent className="z-[99999] max-h-[200px] overflow-y-auto">
                  <SelectItem value="none">— انتخاب کنید —</SelectItem>
                  {sortUnits(units).map((u) => (
                    <SelectItem key={u.id} value={u.id}>
                      {getUnitLabel(u)}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {(!editForm.unitId || editForm.unitId === 'none') && (
                <p className="text-[10px] text-amber-600 mt-0.5">
                  انتخاب واحد الزامی است
                </p>
              )}
            </div>

            <div>
              <Label className="text-xs">قیمت خرید (ریال)</Label>
              <Input
                type="text"
                inputMode="numeric"
                value={formatToPersianWithCommas(editForm.purchasePrice)}
                onChange={(e) =>
                  setEditForm({ ...editForm, purchasePrice: formatToPersianWithCommas(e.target.value) })
                }
                className="mt-1"
                dir="ltr"
              />
            </div>

            <div>
              <Label className="text-xs">قیمت فروش (ریال)</Label>
              <Input
                type="text"
                inputMode="numeric"
                value={formatToPersianWithCommas(editForm.salePrice)}
                onChange={(e) =>
                  setEditForm({ ...editForm, salePrice: formatToPersianWithCommas(e.target.value) })
                }
                className="mt-1"
                dir="ltr"
              />
            </div>

            <div>
              <Label className="text-xs">درصد مالیات</Label>
              <Input
                type="text"
                inputMode="numeric"
                value={formatToPersianWithCommas(editForm.taxRate)}
                onChange={(e) =>
                  setEditForm({ ...editForm, taxRate: formatToPersianWithCommas(e.target.value) })
                }
                className="mt-1"
                dir="ltr"
              />
            </div>

            <div>
              <Label className="text-xs">حداقل موجودی هشدار</Label>
              <Input
                type="text"
                inputMode="numeric"
                value={formatToPersianWithCommas(editForm.minStock)}
                onChange={(e) =>
                  setEditForm({ ...editForm, minStock: formatToPersianWithCommas(e.target.value) })
                }
                className="mt-1"
                dir="ltr"
              />
            </div>

            <div className="flex items-center justify-between col-span-1 sm:col-span-2 rounded-lg border border-gray-100 bg-gray-50 px-3 py-2.5">
              <div className="flex flex-col">
                <Label className="text-xs">وضعیت فعال</Label>
                <span className="text-[10px] text-gray-400 mt-0.5">
                  {editForm.isActive ? 'این کالا در فروشگاه نمایش داده می‌شود' : 'این کالا مخفی خواهد بود'}
                </span>
              </div>
              <div className="flex items-center gap-2">
                <span className={`text-xs font-medium transition-colors ${
                  editForm.isActive ? 'text-blue-600' : 'text-gray-400'
                }`}>
                  {editForm.isActive ? 'فعال' : 'غیرفعال'}
                </span>
                <CustomSwitch checked={editForm.isActive} onCheckedChange={(v) => setEditForm({ ...editForm, isActive: v })} />
              </div>
            </div>
          </div>

          <DialogFooter className="gap-2 sm:gap-0">
            <Button variant="outline" onClick={() => setEditDialogOpen(false)} className="h-9">
              انصراف
            </Button>
            <Button
              onClick={handleEditProduct}
              disabled={submitting || editBarcodeIsDuplicate}
              className={`h-9 gap-2 ${!isOnline ? 'bg-amber-600 hover:bg-amber-700' : 'bg-emerald-600 hover:bg-emerald-700'} ${(submitting || editBarcodeIsDuplicate) ? 'opacity-50 cursor-not-allowed' : ''}`}
            >
              {submitting ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : !isOnline ? (
                <CloudOff className="w-4 h-4" />
              ) : null}
              {!isOnline ? 'ذخیره آفلاین' : 'به‌روزرسانی'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ★ Delete Dialog */}
      <Dialog
        open={!!deletingProduct}
        onOpenChange={(v) => !v && setDeletingProduct(null)}
      >
        <DialogContent className="sm:max-w-[400px] w-[calc(100%-2rem)]" dir="rtl">
          <DialogHeader>
            <DialogTitle className="text-sm sm:text-base">حذف کالا</DialogTitle>
            <DialogDescription className="text-xs">
              این عملیات قابل بازگشت نیست.
            </DialogDescription>
          </DialogHeader>
          <div className="flex items-start gap-3 p-3 bg-red-50 rounded-lg">
            <AlertTriangle className="w-5 h-5 text-red-500 flex-shrink-0 mt-0.5" />
            <p className="text-sm text-gray-700">
              آیا از حذف «<strong>{deletingProduct?.name}</strong>» مطمئن هستید؟
              <br />
              <span className="text-xs text-gray-500">
                {deletingProduct?._isOffline
                  ? 'این کالا آفلاین است و از حافظه محلی حذف می‌شود.'
                  : 'اگر فاکتوری داشته باشد، غیرفعال می‌شود.'}
              </span>
            </p>
          </div>
          <DialogFooter className="gap-2 sm:gap-0">
            <Button variant="outline" onClick={() => setDeletingProduct(null)} className="h-9">
              انصراف
            </Button>
            <Button
              onClick={handleDeleteProduct}
              disabled={deleting}
              className="bg-red-600 hover:bg-red-700 h-9 gap-2"
            >
              {deleting ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <Trash2 className="w-4 h-4" />
              )}
              {deletingProduct?._isOffline ? 'حذف' : !isOnline ? 'علامت‌گذاری برای حذف' : 'حذف'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <BarcodePrintModal
        open={printModalOpen}
        onOpenChange={setPrintModalOpen}
        products={allProducts}
      />
    </div>
  )
}